#!/bin/bash
if [[ $USER != 'root' ]]; then
	echo "ขออภัยคุณต้องเรียกใช้งานนี้เป็น root"
	exit
fi
while :
do
	clear
	echo "ตัวเลือกแก้ไขเมนูพอร์ต"
	echo -e "\e[031;1m 1\e[0m) แก้ไขพอร์ต OpenSSH (\e[34;1medit-port-openssh\e[0m)"
	echo -e "\e[031;1m 2\e[0m) แก้ไขพอร์ต Dropbear (\e[34;1medit-port-dropbear\e[0m)"
	echo -e "\e[031;1m 3\e[0m) แก้ไขพอร์ต Squid Proxy (\e[34;1medit-port-squid\e[0m)"
	echo -e "\e[031;1m 4\e[0m) แก้ไขพอร์ต OpenVPN (\e[34;1medit-port-openvpn\e[0m)"
	echo ""
	echo -e "\e[031;1m x\e[0m) Exit"
	echo ""
	read -p "ป้อนตัวเลือกจากนั้นกดปุ่ม ENTER: " option2
	case $option2 in
		1)
		clear
		edit-port-openssh
		exit
		;;
		2)
		clear
		edit-port-dropbear
		exit
		;;
		3)
		clear
		edit-port-squid
		exit
		;;
		4)
		clear
		edit-port-openvpn
		exit
		;;
		x)
		clear
		exit
		;;
	esac
done
cd
