#!/bin/bash
echo "----------------------- AUTOSCRIPT 0970267262 BY เฮียเบิร์ด แงะตลอด -----------------------"
echo " "
echo "===============================================";
echo " ";
if [ -e "/root/log-limit.txt" ]; then
echo "User yang dikick oleh user-limit adalah";
echo "Time - Username - จำนวน Multilogin"
echo "-------------------------------------";
cat /root/log-limit.txt
else
echo " ไม่มีผู้ใช้รายใดที่ใช้เกิน ขีดจำกัด"
echo " หรือ"
echo " ยังไม่มีการเรียกใช้สคริปต์ขีด จำกัด ของผู้ใช้"
fi
echo " ";
echo "===============================================";
echo " ";
echo " ";
