#!/bin/bash
if [ ! -f /usr/local/bin/deleteduser ]; then
    echo "echo "Script Created By เฮียเบิร์ด.com"" > /usr/local/bin/deleteduser
	chmod +x /usr/local/bin/deleteduser
fi
hariini=`date +%d-%m-%Y`
echo "----------------------- AUTOSCRIPT 0970267262 BY เฮียเบิร์ด แงะตลอด -----------------------"
echo " "
echo "--------------------------------------"
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
totalaccounts=`cat /tmp/expirelist.txt | wc -l`
for((i=1; i<=$totalaccounts; i++ ))
       do
       tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
       username=`echo $tuserval | cut -f1 -d:`
       userexp=`echo $tuserval | cut -f2 -d:`
       userexpireinseconds=$(( $userexp * 86400 ))
       tglexp=`date -d @$userexpireinseconds`             
       tgl=`echo $tglexp |awk -F" " '{print $3}'`
       while [ ${#tgl} -lt 2 ]
       do
           tgl="0"$tgl
       done
       while [ ${#username} -lt 15 ]
       do
           username=$username" " 
       done
       bulantahun=`echo $tglexp |awk -F" " '{print $2,$6}'`
       echo "echo "เฮียเบิร์ด.com - User : $username หมดอายุในวันที่ : $tgl $bulantahun"" >> /usr/local/bin/alluser
       todaystime=`date +%s`
       if [ $userexpireinseconds -ge $todaystime ] ;
           then
			:
       else
       echo "echo ""เฮียเบิร์ด.com- Username : $username หมดอายุแล้วในวันที่: $tgl $bulantahun และถูกลบในวันที่: $hariini "" >> /usr/local/bin/deleteduser
	   echo "Username $username ซึ่งหมดอายุเมื่อ $tgl $bulantahun ถูกนำออกจากระบบเรียบร้อยแล้ว $hariini"
       userdel $username
       fi
done
echo " "
echo "สคริปต์ได้รับการดำเนินการเรียบร้อยแล้ว"
echo "--------------------------------------"
echo " "
