#!/bin/bash
if [ -e "/var/lib/premium-script" ]; then
		echo "continue..."
		clear
	else
		mkdir /var/lib/premium-script;
fi
read -p "ใส่ชื่อผู้ใช้ : " username
grep -E "^$username" /etc/ppp/chap-secrets >/dev/null
if [ $? -eq 0 ]; then
echo "ชื่อผู้ใช้มีอยู่แล้วใน VPS ของคุณ"
exit 0
else
read -p "ใส่รหัสผ่าน : " password
read -p "ระยะเวลาบัญชี (วัน): " masa_aktif

today=`date +%s`
masa_aktif_detik=$(( $masa_aktif * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')
clear
echo "กำลังเชื่อมต่อกับ เฮียเบิร์ด.com..."
sleep 0.5
echo "กำลังสร้างบัญชี ..."
sleep 0.2
echo "กำลังสร้างโฮสต์ ..."
sleep 0.2
echo "สร้างชื่อผู้ใช้ใหม่ของคุณ: $username"
sleep 0.2
echo "สร้างรหัสผ่านสำหรับ $username"
sleep 0.3
MYIP=$(wget -qO- ipv4.icanhazip.com)
echo "$username	*	$password	*" >> /etc/ppp/chap-secrets
echo "$username *   $password   *  $saat_expired"  >> /var/lib/premium-script/data-user-pptp
  clear
  echo "----------------------- AUTOSCRIPT 0970267262 BY เฮียเบิร์ด แงะตลอด -----------------------"
  echo " "
  echo " "
  echo "สร้างบัญชีผู้ใช้ดังกล่าวแล้ว"
  echo "---------------------------------------"
  echo "   Host            : $MYIP"
  echo "   Username        : $username"
  echo "   Password        : $password"
  echo "   Expired         : $tanggal_expired_display"
  echo "--------------------------------------"
  echo " "
fi
