#!/bin/bash
last | grep ppp | grep still | awk '{print " ",$1," - " $3 }' > /tmp/login-db-pptp.txt;
echo "----------------------- AUTOSCRIPT 0970267262 BY เฮียเบิร์ด แงะตลอด -----------------------"
echo " "
echo "===============================================";
echo " "
echo " "
echo "การตรวจสอบการเข้าสู่ระบบผู้ใช้ PPTP VPN";
echo "(Username - IP)";
echo "-------------------------------------";
cat /tmp/login-db-pptp.txt
echo " "
echo " "
echo " "
echo "===============================================";
echo " ";
echo " ";
