#!/bin/bash
read -p "ป้อนชื่อผู้ใช้ที่เปลี่ยนรหัสผ่าน: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "ป้อนรหัสผ่านใหม่สำหรับผู้ใช้ $username: " password

clear
echo "Connecting to id เฮียเบิร์ด.com..."
sleep 0.5
echo "เปลี่ยนรหัสผ่าน..."
sleep 0.5
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  clear
  echo "----------------------- AUTOSCRIPT 0970267262 BY เฮียเบิร์ด แงะตลอด -----------------------"
  echo " "
  echo " "
  echo "---------------------------------------"
  echo -e "รหัสผ่านสำหรับผู้ใช้ ${blue}$username${NC} Sudah berhasil di ganti."
  echo -e "รหัสผ่านใหม่สำหรับผู้ใช้ ${blue}$username${NC} adalah ${red}$password${NC}"
  echo "--------------------------------------"
  echo " "

else
echo -e "Username ${red}$username${NC} ไม่พบใน VPS ของคุณ"
exit 0
fi
